"""modify auth table name to app

Revision ID: 1f3f33a4fab0
Revises: 3367c1f8ca4a
Create Date: 2020-11-19 04:37:55.917097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3f33a4fab0'
down_revision = '3367c1f8ca4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x_sh_id', sa.String(length=255), nullable=True),
    sa.Column('x_sh_key', sa.String(length=255), nullable=True),
    sa.Column('x_sh_master', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('auth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('x_sh_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('x_sh_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('x_sh_master', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='auth_pkey')
    )
    op.drop_table('app')
    # ### end Alembic commands ###
