"""modify auth table

Revision ID: 333d6a822cff
Revises: 1f3f33a4fab0
Create Date: 2020-11-19 05:36:54.999694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333d6a822cff'
down_revision = '1f3f33a4fab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('appid', sa.String(length=255), nullable=True))
    op.add_column('app', sa.Column('appkey', sa.String(length=255), nullable=True))
    op.add_column('app', sa.Column('appmaster', sa.String(length=255), nullable=True))
    op.drop_column('app', 'x_sh_id')
    op.drop_column('app', 'x_sh_key')
    op.drop_column('app', 'x_sh_master')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('x_sh_master', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('app', sa.Column('x_sh_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('app', sa.Column('x_sh_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('app', 'appmaster')
    op.drop_column('app', 'appkey')
    op.drop_column('app', 'appid')
    # ### end Alembic commands ###
