"""modify user activity

Revision ID: 435052a521f2
Revises: 4f8d71609534
Create Date: 2020-12-05 09:42:42.410741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435052a521f2'
down_revision = '4f8d71609534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activity')
    # ### end Alembic commands ###
