"""modify auth table unique appid

Revision ID: 4cf267e383c8
Revises: 333d6a822cff
Create Date: 2020-11-19 21:45:57.740448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cf267e383c8'
down_revision = '333d6a822cff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'app', ['appid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'app', type_='unique')
    # ### end Alembic commands ###
