"""add user model's links field

Revision ID: 82ce62a7b674
Revises: 9824cac74f00
Create Date: 2020-12-09 13:02:02.005462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '82ce62a7b674'
down_revision = '9824cac74f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('links', postgresql.ARRAY(sa.Integer()), server_default='{}', nullable=True))
    op.add_column('users', sa.Column('links', postgresql.ARRAY(sa.Integer(), dimensions=1), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'links')
    op.drop_column('tags', 'links')
    # ### end Alembic commands ###
