"""modify sites and tags array field

Revision ID: 844fbeba4059
Revises: 435052a521f2
Create Date: 2020-12-07 21:10:57.609751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '844fbeba4059'
down_revision = '435052a521f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('site', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('tags', 'sites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('sites', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_column('tags', 'site')
    # ### end Alembic commands ###
